'use client';
import Link from '@/app/link';
import { usePathname } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

import {services,projects} from './data';
export function Dots(){return <span className="dots" aria-hidden="true">{Array.from({length:9},(_,i)=><i key={i}/>)}</span>}
export function Logo(){return <Link href="/" className="logo" aria-label="Kiani motions home"><span className="kiani-mark" aria-hidden="true">K</span><span>Kiani <span className="brand-motion">motions</span></span></Link>}
export function Shell({children}:{children:React.ReactNode}){const path=usePathname();const [open,setOpen]=useState(false);useEffect(()=>{setOpen(false);const motion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const items=document.querySelectorAll<HTMLElement>('.section-heading, .project-card, .service-card, .featured-service-card, .journey>div, .award, .team-row, .leader-card, .cta-panel, .contact-grid>div, .contact-form, .auth-panel, .video-coming, .video-card');items.forEach((el,i)=>{el.classList.add('motion-item');el.style.setProperty('--reveal-delay',`${(i%3)*85}ms`)});const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.08});items.forEach(el=>observer.observe(el));const countObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target as HTMLElement;countObserver.unobserve(el);const final=el.dataset.count||'';const value=parseInt(final.replace(/,/g,''));if(motion||isNaN(value)||final.includes('/'))return;const suffix=final.replace(/[\d,]/g,'');const start=performance.now();function tick(now:number){const p=Math.min((now-start)/1400,1);el.textContent=Math.round(value*(1-Math.pow(1-p,3))).toLocaleString('en-US')+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(el=>countObserver.observe(el));return()=>{observer.disconnect();countObserver.disconnect()}},[path]);return <><a className="skip" href="#main">Skip to content</a><div className="scroll-progress" aria-hidden="true"/><header className="header wrap"><Logo/><nav id="main-navigation" aria-label="Main navigation" className={open?'nav open':'nav'}>{[['/','Home'],['/services','Services'],['/portfolio','Portfolio'],['/about','About'],['/contact','Contact']].map(([url,label])=><Link key={url} href={url} className={(url==='/'?path===url:path.startsWith(url))?'active':''} aria-current={path===url?'page':undefined}>{label}</Link>)}</nav><Link href="https://calendly.com/mskiani2277/kianimotions" className="pill header-cta">Book a call <span aria-hidden="true">↗</span></Link><details className="mobile-nav"><summary aria-label="Open mobile navigation">Menu<span>＋</span></summary><nav aria-label="Mobile navigation">{[['/','Home'],['/services','Services'],['/portfolio','Portfolio'],['/about','About'],['/contact','Contact']].map(([url,label])=><Link href={url} key={url}>{label}<span>↗</span></Link>)}</nav></details></header><main id="main">{children}</main><Footer/><div className="grain" aria-hidden="true"/></>}
export function Footer(){return <footer><div className="wrap footer-grid"><div><Logo/><p>We bring ideas to life through design, technology, and a little creative courage.</p><Link href="https://calendly.com/mskiani2277/kianimotions" className="text-link">Book a call <span aria-hidden="true">↗</span></Link></div><div><h3>Services</h3>{services.slice(0,4).map(s=><Link href={'/services/'+s.slug} key={s.slug}>{s.name}</Link>)}</div><div><h3>Company</h3><Link href="/about">About Us</Link><Link href="/portfolio">Portfolio</Link><Link href="/contact">Contact</Link></div></div><div className="wrap footer-bottom"><div><Link href="/privacy">Privacy Policy</Link><Link href="/disclaimer">Disclaimer</Link></div><span>© {new Date().getFullYear()} Kiani motions. All rights reserved.</span></div></footer>}
export function Stats(){return <div className="stats wrap reveal"><Dots/>{[['1,933','Shorts','Delivered'],['98%','Client','Satisfaction'],['7','Years of','Experience'],['24/7','Support','Available']].map(([n,a,b])=><div className={b==='Experience'?'stat stat-experience':'stat'} key={n}><strong data-count={n}>{n}</strong><span>{a}<br/>{b}</span></div>)}<Dots/></div>}
export function Heading({title,text,href}:{title:string,text?:string,href?:string}){return <div className="section-heading"><div><h2>{title}<Dots/></h2>{text&&<p>{text}</p>}</div>{href&&<Link className="pill outline" href={href}>Show All <span>↗</span></Link>}</div>}
function TrustBadge(){return <div className="hero-trust"><div className="trust-portraits" aria-hidden="true">{[0,1,2,3,4].map(i=><span key={i} style={{backgroundPosition:`${-45-i*33}px -29px`}}/>)}</div><div><div className="trust-stars" aria-label="5 stars">{[0,1,2,3,4].map(i=><span aria-hidden="true" key={i} style={{animationDelay:`${i*.18}s`}}>★</span>)}</div><p>Trusted by <strong>500+ Businesses &amp; Founders</strong></p></div></div>}
export function Hero(){return <section className="hero wrap"><span className="ghost-word" aria-hidden="true">KIANI MOTIONS</span><div className="hero-copy"><span className="eyebrow">Independent minds. Extraordinary ideas.</span><h1 className="animated-headline"><span className="headline-line"><span>Turning <em className="selected">Ideas</em> Into</span></span><span className="headline-line"><span>Digital Reality</span></span></h1><p>We blend bold design with smart technology to build brands, websites, and digital experiences that move your business forward.</p><div className="actions"><Link className="pill" href="https://calendly.com/mskiani2277/kianimotions">Book a call <span aria-hidden="true">↗</span></Link><Link className="text-link" href="/portfolio">See Our Work <span>→</span></Link></div><TrustBadge/></div><div className="hero-art"><div className="art-glow"/><img className="character" src="/assets/character.webp" alt="Joyful illustrated designer wearing a red sweater" fetchPriority="high"/><span className="art-note">A little imagination.<br/>Endless possibilities.</span></div></section>}
export function ProjectGrid({filter=false,category='All Projects'}:{filter?:boolean,category?:string}){return <>{filter&&<div className="filters" aria-label="Filter projects">{['All Projects',...projects.map(p=>p.category)].map(c=><Link href={c==='All Projects'?'/portfolio':'/portfolio?category='+encodeURIComponent(c)} aria-current={category===c?'true':undefined} className={category===c?'filter selected-filter':'filter'} key={c}>{c}</Link>)}</div>}<div className="project-grid" key={category} aria-live="polite">{projects.map((p,i)=>(category==='All Projects'||p.category===category)&&<Link href={'/portfolio/'+i} className="project-card" key={p.name}><div className="project-image"><img src={'/assets/project-'+i+'.webp'} alt={p.name+' website design'} width="620" height="314" loading="lazy"/><span className="project-open">View project ↗</span></div><div className="project-caption"><div><h3>{p.name}</h3><span>{p.category}</span></div><span className="round-arrow">↗</span></div></Link>)}</div></>}
const featuredServices = [
 {code:'GD',name:'Graphic Design',items:['Brand identity & visual systems','Campaign & social graphics','YouTube thumbnails','Presentation & pitch decks','Advertising creative']},
 {code:'VE',name:'Video Editing',items:['Short-form reels & shorts','YouTube & long-form videos','Podcast editing','Captions, sound & colour','Social & promotional ads']},
 {code:'MG',name:'Motion Graphics',items:['Logo animation','Animated typography','Titles & transitions','Brand motion systems','Product & social animation']},
 {code:'DM',name:'Digital Marketing',items:['Campaign planning','Social media content','Audience-focused messaging','Advertising creative','Connected brand campaigns']},
 {code:'WD',name:'Web Development',items:['Business websites','Landing pages','Responsive layouts','Purposeful interactions','Website improvements']},
 {code:'SEO',name:'SEO Optimization',items:['On-page optimization','Content structure','Metadata & headings','Technical foundations','Search-friendly pages']}
];
export function ServiceGrid(){return <div className="featured-service-grid">{featuredServices.map(s=><article className="featured-service-card" key={s.code}><div className="featured-service-title"><span className="service-monogram" aria-hidden="true">{s.code}</span><h3>{s.name}</h3></div><ul>{s.items.map(item=><li key={item}>{item}</li>)}</ul><Link href="https://calendly.com/mskiani2277/kianimotions" className="pill service-booking" aria-label={`Book a call to discuss ${s.name.toLowerCase()}`}>Book a call to discuss <span aria-hidden="true">↗</span></Link></article>)}</div>}

export function Team(){return <section className="wrap section leadership" id="team"><div className="section-heading leadership-heading"><div><span className="eyebrow">THE PEOPLE BEHIND KIANI MOTIONS</span><h2>Meet the <em>Team.</em></h2><p>Two perspectives. One commitment to your growth.</p></div></div><div className="leadership-grid">{[{name:'Nabeel Kiani',focus:'Growth & Client Acquisition',photo:'/assets/nabeel-kiani.png',initials:'NK'},{name:'Second Partner',focus:'Operations & Delivery',initials:'SP'}].map(person=><article className="leader-card" key={person.name}><div className="leader-portrait">{person.photo?<img src={person.photo} alt={person.name} width="1047" height="1501" loading="lazy"/>:<div className="leader-monogram" aria-label="Second Partner initials"><span>SP</span><i aria-hidden="true"/></div>}</div><div className="leader-info"><h3>{person.name}</h3><p className="leader-role">Managing Director</p><p>{person.focus}</p><Link href="https://calendly.com/mskiani2277/kianimotions" className="pill leader-call" aria-label={'Schedule a call with '+person.name}>Schedule a call <span aria-hidden="true">↗</span></Link></div></article>)}</div></section>}
export function Testimonials(){const [index,setIndex]=useState(0);const [ready,setReady]=useState(false);useEffect(()=>setReady(true),[]);const items=[['Daniel Carter','“A fresh perspective, thoughtful details, and a team that genuinely listened. The result brought our vision to life.”'],['Sarah Kim','“From the first conversation to the final design, every step felt clear, collaborative, and creative.”'],['David Chen','“A digital experience that feels as good as it looks. The attention to detail makes all the difference.”']];return <section className="wrap section reveal"><Heading title="Experiences That Inspire"/><div className="testimonial"><div className="avatars">{[0,1,2,3].map(i=><img key={i} src={'/assets/person-'+i+'.webp'} alt="" width="52" height="52"/>)}</div><blockquote key={index} aria-live="polite"><span className="stars" aria-label="5 out of 5 stars">★★★★★</span><p>{items[index][1]}</p><cite>{items[index][0]} <span>· Design collaboration</span></cite></blockquote><div className="carousel-controls"><Button type="button" disabled={!ready} variant="outline" aria-label="Previous testimonial" onClick={()=>setIndex((index+2)%3)}>←</Button><span>0{index+1} / 03</span><Button type="button" disabled={!ready} aria-label="Next testimonial" onClick={()=>setIndex((index+1)%3)}>→</Button></div><small className="sample-note">Illustrative testimonials from the design concept.</small></div></section>}
export function CTA(){return <section className="wrap section reveal"><div className="cta-panel"><div><span className="eyebrow">Big things start with a conversation.</span><h2>Let’s Build<br/>Something <em>Amazing</em></h2><p>Have an idea in mind? Let’s turn it into something people will love.</p><Link href="https://calendly.com/mskiani2277/kianimotions" className="pill">Book a call <span aria-hidden="true">↗</span></Link></div><img src="/assets/character.webp" alt="" width="300" height="530" loading="lazy"/></div></section>}
export function PageHero({title,accent,word}:{title:string,accent:string,word:string}){return <section className="page-hero wrap"><span className="ghost-word" aria-hidden="true">{word}</span><span className="eyebrow">KIANI MOTIONS / {word.toUpperCase()}</span><h1 className="animated-headline"><span className="headline-line"><span>{title}</span></span><span className="headline-line"><span><em className="selected">{accent}</em></span></span></h1><Dots/></section>}

